import React, { useState } from 'react';
import { AlertTriangle } from 'lucide-react';
import { Alert, AlertStatus } from '../types';
import { api } from '../api/client';

interface AlertsViewProps {
  alerts: Alert[];
  onRefresh: () => void;
}

export const AlertsView: React.FC<AlertsViewProps> = ({ alerts, onRefresh }) => {
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);

  const handleStatusChange = async (status: AlertStatus) => {
    if (!selectedAlert) return;
    try {
      const updated = await api.updateAlertStatus(selectedAlert.id, status);
      setSelectedAlert(updated);
      onRefresh();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h3 className="text-base font-mono font-bold text-slate-100 uppercase tracking-wider flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-rose-500" /> Alert Triage & Response Center
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            Real-time security alerts generated by deterministic rule correlation engine.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className={`bg-slate-950 border border-slate-800 rounded-xl p-5 ${selectedAlert ? 'lg:col-span-2' : 'lg:col-span-3'}`}>
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs font-mono text-slate-300">
              <thead className="bg-slate-900 text-slate-400 uppercase text-[10px] border-b border-slate-800">
                <tr>
                  <th className="p-3">Status</th>
                  <th className="p-3">Severity</th>
                  <th className="p-3">Rule Code</th>
                  <th className="p-3">Host</th>
                  <th className="p-3">MITRE</th>
                  <th className="p-3">Triggered</th>
                  <th className="p-3 text-right">Inspect</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/50">
                {alerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-slate-900/60 transition-colors">
                    <td className="p-3">
                      <span className="px-2 py-0.5 rounded text-[10px] bg-slate-800 text-slate-300 font-bold">
                        {alert.status}
                      </span>
                    </td>
                    <td className="p-3">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        alert.severity === 'CRITICAL' ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30' :
                        alert.severity === 'HIGH' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' :
                        alert.severity === 'MEDIUM' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-emerald-500/20 text-emerald-400'
                      }`}>
                        {alert.severity}
                      </span>
                    </td>
                    <td className="p-3 font-semibold text-cyan-400">{alert.rule_code}</td>
                    <td className="p-3 text-slate-200">{alert.host}</td>
                    <td className="p-3">
                      <span className="px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 text-[10px]">
                        {alert.mitre_technique_id}
                      </span>
                    </td>
                    <td className="p-3 text-slate-400">{new Date(alert.created_at).toLocaleTimeString()}</td>
                    <td className="p-3 text-right">
                      <button
                        onClick={() => setSelectedAlert(alert)}
                        className="px-3 py-1 bg-slate-900 border border-slate-800 hover:border-slate-700 text-slate-200 rounded text-[11px] font-mono transition-colors"
                      >
                        Inspect
                      </button>
                    </td>
                  </tr>
                ))}
                {alerts.length === 0 && (
                  <tr>
                    <td colSpan={7} className="p-8 text-center text-slate-500">
                      No active alerts registered in database.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Alert Triage Drawer */}
        {selectedAlert && (
          <div className="bg-slate-950 border border-slate-800 rounded-xl p-5 space-y-4 font-mono">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <h4 className="text-xs font-bold text-slate-200 uppercase">Alert Detail Triage</h4>
              <button onClick={() => setSelectedAlert(null)} className="text-xs text-slate-500 hover:text-slate-300">
                Close
              </button>
            </div>

            <div className="space-y-2 text-xs">
              <div className="p-3 bg-slate-900 border border-slate-800 rounded-lg space-y-1">
                <p className="text-slate-400 text-[10px] uppercase">Reason & Detection Context</p>
                <p className="text-slate-200 font-semibold">{selectedAlert.reason}</p>
              </div>

              <div className="grid grid-cols-2 gap-2 text-[11px]">
                <div className="p-2 bg-slate-900 border border-slate-800 rounded">
                  <span className="text-slate-500">Rule Code:</span>
                  <p className="text-cyan-400 font-bold">{selectedAlert.rule_code}</p>
                </div>
                <div className="p-2 bg-slate-900 border border-slate-800 rounded">
                  <span className="text-slate-500">MITRE Technique:</span>
                  <p className="text-amber-400 font-bold">{selectedAlert.mitre_technique_id}</p>
                </div>
              </div>

              <div className="pt-3">
                <p className="text-[10px] text-slate-500 uppercase mb-2">Update Triage Status</p>
                <div className="grid grid-cols-2 gap-2 text-xs">
                  {(['NEW', 'ACKNOWLEDGED', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE'] as AlertStatus[]).map((st) => (
                    <button
                      key={st}
                      onClick={() => handleStatusChange(st)}
                      className={`px-2 py-1.5 rounded text-[10px] font-bold border transition-colors ${
                        selectedAlert.status === st
                          ? 'bg-cyan-500 text-black border-cyan-400'
                          : 'bg-slate-900 text-slate-300 border-slate-800 hover:border-slate-700'
                      }`}
                    >
                      {st}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
